name: 📚 Documentation
description: Report an issue related to the [cpr sdk package](https://github.com/climatepolicyradar/cpr-sdk)
labels: 'documentation'

body:
- type: textarea
  attributes:
    label: 📚 The doc issue
    description: >
      A clear and concise description of what content in the [cpr sdk](https://github.com/climatepolicyradar/cpr-sdk) is an issue.
  validations:
    required: true
- type: textarea
  attributes:
    label: Suggest a potential alternative/fix
    description: >
      Tell us how we could improve the documentation in this regard.
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
