name: pre-commit-checks
description: Run pre-commit checks

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
        cache: poetry

    - shell: bash
      run: pipx install poetry==1.8.2

    - name: Install python or load from cache with dependencies
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
        cache: poetry

    - shell: bash
      run: poetry install --all-extras --with dev --with search_tests --with tools_agents

    - shell: bash
      run: poetry run pre-commit run --all-files
