name: pre-commit-checks
description: Run pre-commit checks

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - shell: bash
      run: |
        pipx install poetry==1.3.2

    - name: Install python or load from cache with dependencies
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "poetry"

    - shell: bash
      run: |
        poetry install --all-extras --with dev

    - shell: bash
      run: |
        poetry run pre-commit run --all-files
