name: pre-commit-checks
description: Run pre-commit checks

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: make install

    - name: Lint
      shell: bash
      run: make lint-all
