name: check-placeholder-version
description: Check that the placeholder version in the pyproject.toml is 0.0.0

runs:
  using: composite
  steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: "3.10"    

  - shell: bash
    run: | 
      echo "PYPROJECT_VERSION=$(poetry version --short)"

      if [[ "$PYPROJECT_VERSION" == "0.0.0" ]]; then
        echo "The pyproject.toml version is the correct placeholder version."
      else
        echo "The pyproject.toml version is NOT the correct placeholder version"
        exit 1
      fi
  