name: publish
on:
  release:
    types:
      - published
  pull_request:  

jobs:
  precommit-checks:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Run pre-commit checks
      uses: ./.github/actions/precommit-checks

  fixme-checks:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Run fixme checks 
      uses: ./.github/actions/fixme-checks

  package-version-checks:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v4
   
    - name: Run package version checks
      uses: ./.github/actions/check-version-release

  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v4
    
    - name: Run tests
      uses: ./.github/actions/test

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # needs: [precommit-checks, fixme-checks, package-version-checks, test]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry==1.7.1

      - name: Install python or load from cache with dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          # cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install

      - name: Build 
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
          pipx inject poetry "poetry-dynamic-versioning[plugin]"
          poetry build 

      - name: Publish 
        run: |
          poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
