name: publish
on:
  release:
    types:
      - published
  # TODO: REMOVE THIS BEFORE PUBLISHING
  pull_request:

jobs:
  precommit-checks:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Run pre-commit checks
      uses: ./.github/actions/precommit-checks

  fixme-checks:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Run fixme checks 
      uses: ./.github/actions/fixme-checks

  package-version-checks:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v4
   
    - name: Run package version checks
      uses: ./.github/actions/check-version-release

  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v4
    
    - name: Run tests
      uses: ./.github/actions/test

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # TODO REMOVE 
    # needs: [precommit-checks, fixme-checks, package-version-checks, test]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.3.2

      - name: Install python or load from cache with dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install

      - name: Set The Poetry Version from the Package 
        run: |
          export "CURRENT_VERSION=$(python -c 'from src import cpr_sdk; print(cpr_sdk.__version__)')"
          poetry version "${CURRENT_VERSION}-alpha"
          poetry version

      - name: Build 
        run: |
          poetry build 

      - name: Publish 
        run: |
          poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
